// flow-typed signature: a28b0bdcbbde70e5133e48dfd3cf1d0b
// flow-typed version: <<STUB>>/gatsby-plugin-flow_v^1.1.9/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-flow/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-flow/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-flow/gatsby-node'>;
}
declare module 'gatsby-plugin-flow/index' {
  declare module.exports: $Exports<'gatsby-plugin-flow'>;
}
declare module 'gatsby-plugin-flow/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-flow'>;
}
