# Generated by Django 2.2.6 on 2019-10-11 06:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
